### ISSUE TITLE
FAB button items off center

### ISSUE THREAD

**Issue by MaxBleggi** [kciter/KCFloatingActionButton#55]
The FAB is at the bottom right in the beginning

<img width="236" alt="screenshot 2016-07-25 17 46 20" src="https://cloud.githubusercontent.com/assets/12599003/17118724/f1bb42be-528f-11e6-9739-ad89840badf6.png">

Then I present another screen modally which has a date picker popup from bottom  like so
<img width="370" alt="screenshot 2016-07-25 17 46 43" src="https://cloud.githubusercontent.com/assets/12599003/17118756/2297dfc8-5290-11e6-92fc-897beebc5ce6.png">

After that I unwind from the previous segue and the FAB has been repositioned to the middle of the screen (about the same distance above its original position as the data picker is tall). This behavior only happens when that picker pops up from the bottom of the screen.

I click on the FAB that's now in the middle of the screen then is repositions it self back to the bottom right but there is one issue

<img width="239" alt="screenshot 2016-07-25 17 46 52" src="https://cloud.githubusercontent.com/assets/12599003/17118829/8f94e990-5290-11e6-8500-35b902e211f0.png">

Tried solving the issue like so:

```
// get original position of fab
xPos = FAB.frame.origin.x
yPos = FAB.frame.origin.y
```

```
@IBAction func unwindSegue(unwindSegue: UIStoryboardSegue)
 {
       // when unwind occurs, reposition fab    
        FAB.frame.origin.x = xPos
        FAB.frame.origin.y = yPos
 }
```

This works to reposition the FAB after the unwind occurs, but the button items still appear off center when the FAB is clicked on

**Comment by kciter** [comment]
Hello @MaxBleggi 
What is KCFAB version and KCFAB type(on window or on controller) you are using?

**Comment by MaxBleggi** [comment]
Hello @kciter  Thank you for the help,

I just added your libraries to my project on June 20th. I installed them manually and don't see any versioning in the source.

I added the FAB via the storyboard like so: I added a UIView to the screen then set its class to KCFloatingActionButton

<img width="292" alt="screenshot 2016-08-02 14 51 39" src="https://cloud.githubusercontent.com/assets/12599003/17341044/c843c0b4-58c0-11e6-9621-8b1017e1207b.png">



Here's its reference in the ViewController

` @IBOutlet var FAB: KCFloatingActionButton!`

then later I add the items

<img width="609" alt="screenshot 2016-08-02 15 00 10" src="https://cloud.githubusercontent.com/assets/12599003/17341288/de99c3c6-58c1-11e6-8099-e67dee7e8b04.png">

**Comment by kciter** [comment]
Hello, @MaxBleggi 
Sorry, I'm too late and I can't reproduce. 😢 
Please use the latest version.
https://github.com/kciter/KCFloatingActionButton/tree/1.4.0/KCFloatingActionButton

**Comment by MaxBleggi** [comment]
No problem @kciter 

I've implemented the latest version but it doesn't seem to fix it.... I've created a very simple project that reproduces the bug here: https://www.dropbox.com/s/zgf2suvyjh53lxd/ExampleOfBug.zip?dl=0

I was going to add a date picker to come up like in my original project but I noticed that in this version, the bug occurs every time I unwind back from any of the view controllers I present modally.

Steps to reproduce:
1. Press on any of the FAB items which will modally segue you to a new controller (doesn't matter which one is picked)
2. press the cancel bar item button in that new screen. This will unwind you back to the previous screen which contains the FAB
3. press on the fab again and the items are shifted to the left compared to where they should be.

I'm using xCode 7.3.1

**Comment by kciter** [comment]
Thanks @MaxBleggi !
I've found the bug with your help.

Problem is `PopAnimation` and I fixed the bug.

Below is version of solving the problem.
https://github.com/kciter/KCFloatingActionButton/tree/1.4.1

**Comment by mattbarker016** [comment]
I'm still experiencing this bug using the PopAnimation. I have the button on iPad on the left side on the screen. The images are off too.

<img width="102" alt="messages image 555342164" src="https://user-images.githubusercontent.com/8039928/29856236-7d1e49d0-8d1f-11e7-98cf-6ca848253fb3.png">
